calc_Bpsi – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
calc_Bpsi Subroutine
23 statements
Source File
subroutine calc_Bpsi()
Uses
math_derivation
global_variables
iso_fortran_env
constants_and_parameters
Arguments
None
Calls
Called by
Contents
None
Call graph
calc_bpsi calls math_diff_r_9point, math_diff_z_9point
math_diff_r_9point calls math_diff_r_9point_complexfunc, math_diff_r_9point_realfunc
math_diff_z_9point calls math_diff_z_9point_complexfunc, math_diff_z_9point_realfunc
calc_hpsi calls calc_bpsi
calc_hf_by_imaginary_time_evolution calls calc_hpsi
calc_ground_state calls calc_hf_by_imaginary_time_evolution
main calls calc_ground_state