calc_observables – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
calc_observables Subroutine
9 statements
Source File
subroutine calc_observables()
Uses
determine_observables
Arguments
None
Calls
Called by
Contents
None
Call graph
calc_observables calls calc_cm_energy, calc_coulomb_energy, calc_kinetic_energy_by_integrate, calc_skyrme_energy_by_integrate, calc_total_energy
calc_cm_energy calls calc_pc2_exv
calc_coulomb_energy calls volume_integrate
calc_kinetic_energy_by_integrate calls volume_integrate
calc_skyrme_energy_by_integrate calls volume_integrate
calc_pc2_exv calls volume_integrate
calc_ground_state calls calc_observables
main calls calc_ground_state