nine_point_poisson_by_lapack – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
nine_point_poisson_by_lapack Subroutine
76 statements
Source File
public subroutine nine_point_poisson_by_lapack(rho_p, coulomb)
Uses
global_variables
iso_fortran_env
constants_and_parameters
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: rho_p(:,:)
real(kind=real64), intent(out) :: coulomb(:,:)
Calls
Called by
Contents
Call graph
nine_point_poisson_by_lapack calls get_k, use_dgesv
use_dgesv calls dgesv
calc_coulomb_pot calls nine_point_poisson_by_lapack
calc_pot_u_np calls calc_coulomb_pot
calc_pot_u calls calc_pot_u_np
calc_meanfield calls calc_pot_u
calc_ground_state calls calc_meanfield
main calls calc_ground_state