calc_meanfield – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
calc_meanfield Subroutine
7 statements
Source File
subroutine calc_meanfield()
Uses
determine_meanfield_potential
Arguments
None
Calls
Called by
Contents
None
Call graph
calc_meanfield calls calc_pot_b, calc_pot_u, calc_pot_w
calc_pot_u calls calc_pot_u_np
calc_pot_u_np calls b0pt, b0t, b1pt, b1t, b2pt, b2t, b3pt, b3pt2, b3t, b4pt, b4t, calc_coulomb_pot, write_u_term
calc_coulomb_pot calls nine_point_poisson_by_lapack
nine_point_poisson_by_lapack calls get_k, use_dgesv
use_dgesv calls dgesv
calc_ground_state calls calc_meanfield
main calls calc_ground_state