calc_spin_orbit_density_and_div – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
calc_spin_orbit_density_and_div Subroutine
78 statements
Source File
subroutine calc_spin_orbit_density_and_div()
Uses
global_variables
iso_fortran_env
ieee_arithmetic
constants_and_parameters
math_derivation
Arguments
None
Calls
Called by
Contents
None
Call graph
calc_spin_orbit_density_and_div calls math_diff_r_9point, math_diff_z_9point
math_diff_r_9point calls math_diff_r_9point_complexfunc, math_diff_r_9point_realfunc
math_diff_z_9point calls math_diff_z_9point_complexfunc, math_diff_z_9point_realfunc
calc_densities calls calc_spin_orbit_density_and_div
calc_ground_state calls calc_densities
main calls calc_ground_state