calc_ground_state – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
calc_ground_state Subroutine
76 statements
Source File
subroutine calc_ground_state()
Uses
write_to_file
global_variables
iso_fortran_env
constants_and_parameters
Arguments
None
Calls
Called by
Contents
None
Call graph
calc_ground_state calls calc_densities, calc_derivation_of_wavefunction, calc_hf_by_imaginary_time_evolution, calc_meanfield, calc_observables, copy_to_occupied_wf, write_d_wavefunction, write_density_and_derivative, write_iter_energy, write_meanfield_energy, write_pot, write_prep_sort, write_wavefunction
calc_densities calls calc_density_and_lap, calc_kinetic_density, calc_spin_orbit_density_and_div
calc_derivation_of_wavefunction calls math_diff_2r_9point, math_diff_2z_9point, math_diff_r_9point, math_diff_z_9point
calc_hf_by_imaginary_time_evolution calls calc_hpsi, calc_hpsi2, calc_imag_evolution, calc_one_particle_energy, is_converge_for_one_e, schmidt_orthogonalization, sort_energy_and_idx
calc_meanfield calls calc_pot_b, calc_pot_u, calc_pot_w
calc_observables calls calc_cm_energy, calc_coulomb_energy, calc_kinetic_energy_by_integrate, calc_skyrme_energy_by_integrate, calc_total_energy
math_diff_2r_9point calls math_diff_2r_9point_realfunc
math_diff_2z_9point calls math_diff_2z_9point_realfunc
math_diff_r_9point calls math_diff_r_9point_complexfunc, math_diff_r_9point_realfunc
math_diff_z_9point calls math_diff_z_9point_complexfunc, math_diff_z_9point_realfunc
calc_cm_energy calls calc_pc2_exv
calc_coulomb_energy calls volume_integrate
calc_density_and_lap calls math_diff_2r_9point, math_diff_2z_9point, math_diff_r_9point, math_diff_z_9point, volume_integrate
calc_hpsi calls calc_bpsi, calc_upsi, calc_wpsi
calc_hpsi2 calls math_diff_2r_9point, math_diff_2z_9point, math_diff_r_9point, math_diff_z_9point
calc_kinetic_energy_by_integrate calls volume_integrate
calc_one_particle_energy calls volume_integrate
calc_pot_u calls calc_pot_u_np
calc_skyrme_energy_by_integrate calls volume_integrate
calc_spin_orbit_density_and_div calls math_diff_r_9point, math_diff_z_9point
schmidt_orthogonalization calls prep_wf_overlap
calc_bpsi calls math_diff_r_9point, math_diff_z_9point
calc_pc2_exv calls volume_integrate
calc_pot_u_np calls b0pt, b0t, b1pt, b1t, b2pt, b2t, b3pt, b3pt2, b3t, b4pt, b4t, calc_coulomb_pot, write_u_term
prep_wf_overlap calls volume_integrate
calc_coulomb_pot calls nine_point_poisson_by_lapack
nine_point_poisson_by_lapack calls get_k, use_dgesv
use_dgesv calls dgesv
main calls calc_ground_state