calc_hf_by_imaginary_time_evolution – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
calc_hf_by_imaginary_time_evolution Subroutine
18 statements
Source File
subroutine calc_hf_by_imaginary_time_evolution()
Uses
global_variables
constants_and_parameters
Arguments
None
Calls
Called by
Contents
None
Call graph
calc_hf_by_imaginary_time_evolution calls calc_hpsi, calc_hpsi2, calc_imag_evolution, calc_one_particle_energy, is_converge_for_one_e, schmidt_orthogonalization, sort_energy_and_idx
calc_hpsi calls calc_bpsi, calc_upsi, calc_wpsi
calc_hpsi2 calls math_diff_2r_9point, math_diff_2z_9point, math_diff_r_9point, math_diff_z_9point
calc_one_particle_energy calls volume_integrate
schmidt_orthogonalization calls prep_wf_overlap
math_diff_2r_9point calls math_diff_2r_9point_realfunc
math_diff_2z_9point calls math_diff_2z_9point_realfunc
math_diff_r_9point calls math_diff_r_9point_complexfunc, math_diff_r_9point_realfunc
math_diff_z_9point calls math_diff_z_9point_complexfunc, math_diff_z_9point_realfunc
calc_bpsi calls math_diff_r_9point, math_diff_z_9point
prep_wf_overlap calls volume_integrate
calc_ground_state calls calc_hf_by_imaginary_time_evolution
main calls calc_ground_state