calc_Wpsi – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
calc_Wpsi Subroutine
13 statements
Source File
subroutine calc_Wpsi()
Uses
global_variables
iso_fortran_env
constants_and_parameters
Arguments
None
Called by
Contents
None
Call graph
calc_hpsi calls calc_wpsi
calc_hf_by_imaginary_time_evolution calls calc_hpsi
calc_ground_state calls calc_hf_by_imaginary_time_evolution
main calls calc_ground_state