get_k – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
get_k Function
7 statements
Source File
public function get_k(r_idx, z_idx) result(k_idx)
Uses
constants_and_parameters
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: r_idx
integer, intent(in) :: z_idx
Return Value integer
Called by
Contents
Call graph
nine_point_poisson_by_lapack calls get_k
three_point_poisson_by_lapack calls get_k
calc_coulomb_pot calls nine_point_poisson_by_lapack
calc_pot_u_np calls calc_coulomb_pot
calc_pot_u calls calc_pot_u_np
calc_meanfield calls calc_pot_u
calc_ground_state calls calc_meanfield
main calls calc_ground_state