Laguerre_nl – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
Laguerre_nl Function
13 statements
Source File
public function Laguerre_nl(n, l, x) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: n
integer(kind=int32), intent(in) :: l
real(kind=real64), intent(in) :: x
Return Value real(kind=real64)
Called by
Contents
Call graph
set_harmonic_occ calls laguerre_nl
prep_initial_wavefunction calls set_harmonic_occ
prep_time_reversal_wavefunction calls set_harmonic_occ
initial_settings calls prep_initial_wavefunction, prep_time_reversal_wavefunction
main calls initial_settings