prep_wf_overlap – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
prep_wf_overlap Function
14 statements
Source File
function prep_wf_overlap(idx_1, idx_2, np_int) result(ovlp)
Uses
math_integrate
global_variables
iso_fortran_env
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: idx_1
integer(kind=int32), intent(in) :: idx_2
integer(kind=int32), intent(in) :: np_int
Return Value real(kind=real64)
Calls
Called by
Contents
Call graph
prep_wf_overlap calls volume_integrate
schmidt_orthogonalization calls prep_wf_overlap
calc_hf_by_imaginary_time_evolution calls schmidt_orthogonalization
calc_ground_state calls calc_hf_by_imaginary_time_evolution
main calls calc_ground_state