Schmidt_orthogonalization – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
Schmidt_orthogonalization Subroutine
24 statements
Source File
subroutine Schmidt_orthogonalization(np_int)
Uses
global_variables
constants_and_parameters
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: np_int
Calls
Called by
Contents
Call graph
schmidt_orthogonalization calls prep_wf_overlap
prep_wf_overlap calls volume_integrate
calc_hf_by_imaginary_time_evolution calls schmidt_orthogonalization
calc_ground_state calls calc_hf_by_imaginary_time_evolution
main calls calc_ground_state