set_harmonic_occ – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
set_harmonic_occ Function
31 statements
Source File
public function set_harmonic_occ(node_r, node_z, mag, r, z, betain) result(normilized_wf)
Uses
global_variables
spacial_function
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: node_r
integer(kind=int32), intent(in) :: node_z
integer(kind=int32), intent(in) :: mag
real(kind=real64), intent(in) :: r
real(kind=real64), intent(in) :: z
real(kind=real64), intent(in) :: betain
Return Value real(kind=real64)
Calls
Called by
Contents
Call graph
set_harmonic_occ calls hermite_n, laguerre_nl
prep_initial_wavefunction calls set_harmonic_occ
prep_time_reversal_wavefunction calls set_harmonic_occ
initial_settings calls prep_initial_wavefunction, prep_time_reversal_wavefunction
main calls initial_settings