sort_energy_and_idx – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
sort_energy_and_idx Subroutine
37 statements
Source File
subroutine sort_energy_and_idx(energy_array, idx)
Uses
iso_fortran_env
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(inout) :: energy_array(:,:)
integer(kind=int32), intent(inout) :: idx(:,:)
Called by
Contents
Call graph
calc_hf_by_imaginary_time_evolution calls sort_energy_and_idx
prep_initial_wavefunction calls sort_energy_and_idx
prep_time_reversal_wavefunction calls sort_energy_and_idx
calc_ground_state calls calc_hf_by_imaginary_time_evolution
initial_settings calls prep_initial_wavefunction, prep_time_reversal_wavefunction
main calls calc_ground_state, initial_settings