volume_integrate – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
volume_integrate Function
22 statements
Source File
public function volume_integrate(f) result(result)
Uses
global_variables
constants_and_parameters
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: f(:,:)
Return Value real(kind=real64)
Called by
Contents
Call graph
calc_coulomb_energy calls volume_integrate
calc_density_and_lap calls volume_integrate
calc_kinetic_energy_by_integrate calls volume_integrate
calc_one_particle_energy calls volume_integrate
calc_pc2_exv calls volume_integrate
calc_skyrme_energy_by_integrate calls volume_integrate
overlap_to_file calls volume_integrate
prep_wf_overlap calls volume_integrate
calc_cm_energy calls calc_pc2_exv
calc_densities calls calc_density_and_lap
calc_hf_by_imaginary_time_evolution calls calc_one_particle_energy, schmidt_orthogonalization
calc_observables calls calc_coulomb_energy, calc_kinetic_energy_by_integrate, calc_skyrme_energy_by_integrate, calc_cm_energy
schmidt_orthogonalization calls prep_wf_overlap
calc_ground_state calls calc_densities, calc_hf_by_imaginary_time_evolution, calc_observables
main calls calc_ground_state