calc_density_and_lap – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
calc_density_and_lap Subroutine
49 statements
Source File
subroutine calc_density_and_lap()
Uses
global_variables
iso_fortran_env
math_integrate
ieee_arithmetic
constants_and_parameters
math_derivation
Arguments
None
Calls
Called by
Contents
None
Call graph
calc_density_and_lap calls math_diff_2r_9point, math_diff_2z_9point, math_diff_r_9point, math_diff_z_9point, volume_integrate
math_diff_2r_9point calls math_diff_2r_9point_realfunc
math_diff_2z_9point calls math_diff_2z_9point_realfunc
math_diff_r_9point calls math_diff_r_9point_complexfunc, math_diff_r_9point_realfunc
math_diff_z_9point calls math_diff_z_9point_complexfunc, math_diff_z_9point_realfunc
calc_densities calls calc_density_and_lap
calc_ground_state calls calc_densities
main calls calc_ground_state