calc_Hpsi2 – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
calc_Hpsi2 Subroutine
103 statements
Source File
subroutine calc_Hpsi2()
Uses
math_derivation
global_variables
iso_fortran_env
constants_and_parameters
Arguments
None
Calls
Called by
Contents
None
Call graph
calc_hpsi2 calls math_diff_2r_9point, math_diff_2z_9point, math_diff_r_9point, math_diff_z_9point
math_diff_2r_9point calls math_diff_2r_9point_realfunc
math_diff_2z_9point calls math_diff_2z_9point_realfunc
math_diff_r_9point calls math_diff_r_9point_complexfunc, math_diff_r_9point_realfunc
math_diff_z_9point calls math_diff_z_9point_complexfunc, math_diff_z_9point_realfunc
calc_hf_by_imaginary_time_evolution calls calc_hpsi2
calc_ground_state calls calc_hf_by_imaginary_time_evolution
main calls calc_ground_state