calc_pot_W – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
calc_pot_W Subroutine
30 statements
Source File
public subroutine calc_pot_W()
Uses
math_derivation
global_variables
iso_fortran_env
constants_and_parameters
Arguments
None
Called by
Contents
None
Call graph
calc_meanfield calls calc_pot_w
calc_ground_state calls calc_meanfield
main calls calc_ground_state