calc_derivation_of_wavefunction – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
calc_derivation_of_wavefunction Subroutine
49 statements
Source File
subroutine calc_derivation_of_wavefunction()
Uses
math_derivation
global_variables
constants_and_parameters
maxval(dble(prep_mag(prep,l)+1)/r_vec(i)*prep_wf_minus)
maxval(-dble(prep_mag(prep,l))/r_vec(i)*prep_wf_plus)
Arguments
None
Calls
Called by
Contents
None
Call graph
calc_derivation_of_wavefunction calls math_diff_2r_9point, math_diff_2z_9point, math_diff_r_9point, math_diff_z_9point
math_diff_2r_9point calls math_diff_2r_9point_realfunc
math_diff_2z_9point calls math_diff_2z_9point_realfunc
math_diff_r_9point calls math_diff_r_9point_complexfunc, math_diff_r_9point_realfunc
math_diff_z_9point calls math_diff_z_9point_complexfunc, math_diff_z_9point_realfunc
calc_ground_state calls calc_derivation_of_wavefunction
main calls calc_ground_state