use_DGESV – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
use_DGESV Subroutine
30 statements
Source File
public subroutine use_DGESV(N, A, b, res_x)
Uses
iso_fortran_env
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: N
real(kind=8), intent(in) :: A(:,:)
real(kind=8), intent(in) :: b(:)
real(kind=8), intent(out) :: res_x(:)
Calls
Called by
Contents
Call graph
use_dgesv calls dgesv
nine_point_poisson_by_lapack calls use_dgesv
calc_coulomb_pot calls nine_point_poisson_by_lapack
calc_pot_u_np calls calc_coulomb_pot
calc_pot_u calls calc_pot_u_np
calc_meanfield calls calc_pot_u
calc_ground_state calls calc_meanfield
main calls calc_ground_state