main – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
main Program
1068 statements
Source File
Uses
write_to_file
ieee_arithmetic
iso_fortran_env
constants_and_parameters
Calls
Contents
Variables
num_iter str tf1 ti1 tr1
Functions
prep_wf_overlap
Subroutines
Schmidt_orthogonalization alloc_fields calc_Bpsi calc_Hpsi calc_Hpsi2 calc_IMAG_Evolution calc_Upsi calc_Wpsi calc_densities calc_density_and_lap calc_derivation_of_wavefunction calc_ground_state calc_hf_by_imaginary_time_evolution calc_kinetic_density calc_meanfield calc_observables calc_one_particle_energy calc_spin_orbit_density_and_div copy_to_occupied_wf dealloc_fields initial_settings is_converge_for_one_E prep_initial_wavefunction prep_time_reversal_wavefunction read_input_parameters sort_energy_and_idx
Variables
Type Attributes Name Initial
integer(kind=int32) :: num_iter
character(len=40) :: str
integer(kind=int32) :: tf1
integer(kind=int32) :: ti1
integer(kind=int32) :: tr1
Functions
function prep_wf_overlap(idx_1, idx_2, np_int) result(ovlp)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: idx_1
integer(kind=int32), intent(in) :: idx_2
integer(kind=int32), intent(in) :: np_int
Return Value real(kind=real64)
Subroutines
subroutine Schmidt_orthogonalization(np_int)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: np_int
subroutine alloc_fields()
Arguments
None
subroutine calc_Bpsi()
Arguments
None
subroutine calc_Hpsi()
Arguments
None
subroutine calc_Hpsi2()
Arguments
None
subroutine calc_IMAG_Evolution(np_int)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: np_int
subroutine calc_Upsi()
Arguments
None
subroutine calc_Wpsi()
Arguments
None
subroutine calc_densities()
Arguments
None
subroutine calc_density_and_lap()
Arguments
None
subroutine calc_derivation_of_wavefunction()
maxval(dble(prep_mag(prep,l)+1)/r_vec(i)*prep_wf_minus)
Read more…
Arguments
None
subroutine calc_ground_state()
Arguments
None
subroutine calc_hf_by_imaginary_time_evolution()
Arguments
None
subroutine calc_kinetic_density()
Arguments
None
subroutine calc_meanfield()
Arguments
None
subroutine calc_observables()
Arguments
None
subroutine calc_one_particle_energy()
Arguments
None
subroutine calc_spin_orbit_density_and_div()
Arguments
None
subroutine copy_to_occupied_wf()
Arguments
None
subroutine dealloc_fields()
Arguments
None
subroutine initial_settings()
Arguments
None
subroutine is_converge_for_one_E(is_converged)
Arguments
Type Intent Optional Attributes Name
logical, intent(out) :: is_converged
subroutine prep_initial_wavefunction()
!!!!--------- prep_number -----------
Arguments
None
subroutine prep_time_reversal_wavefunction()
Arguments
None
subroutine read_input_parameters()
Arguments
None
subroutine sort_energy_and_idx(energy_array, idx)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(inout) :: energy_array(:,:)
integer(kind=int32), intent(inout) :: idx(:,:)
Call graph
main calls alloc_fields, calc_ground_state, dealloc_fields, initial_settings, outputsettings, read_input_parameters
calc_ground_state calls calc_densities, calc_derivation_of_wavefunction, calc_hf_by_imaginary_time_evolution, calc_meanfield, calc_observables, copy_to_occupied_wf, write_d_wavefunction, write_density_and_derivative, write_iter_energy, write_meanfield_energy, write_pot, write_prep_sort, write_wavefunction
initial_settings calls prep_initial_wavefunction, prep_time_reversal_wavefunction
outputsettings calls make_one_file
calc_densities calls calc_density_and_lap, calc_kinetic_density, calc_spin_orbit_density_and_div
calc_derivation_of_wavefunction calls math_diff_2r_9point, math_diff_2z_9point, math_diff_r_9point, math_diff_z_9point
calc_hf_by_imaginary_time_evolution calls calc_hpsi, calc_hpsi2, calc_imag_evolution, calc_one_particle_energy, is_converge_for_one_e, schmidt_orthogonalization, sort_energy_and_idx
calc_meanfield calls calc_pot_b, calc_pot_u, calc_pot_w
calc_observables calls calc_cm_energy, calc_coulomb_energy, calc_kinetic_energy_by_integrate, calc_skyrme_energy_by_integrate, calc_total_energy
prep_initial_wavefunction calls calc_occ_energy, set_harmonic_occ, sort_energy_and_idx
prep_time_reversal_wavefunction calls calc_occ_energy, set_harmonic_occ, sort_energy_and_idx
math_diff_2r_9point calls math_diff_2r_9point_realfunc
math_diff_2z_9point calls math_diff_2z_9point_realfunc
math_diff_r_9point calls math_diff_r_9point_complexfunc, math_diff_r_9point_realfunc
math_diff_z_9point calls math_diff_z_9point_complexfunc, math_diff_z_9point_realfunc
calc_cm_energy calls calc_pc2_exv
calc_coulomb_energy calls volume_integrate
calc_density_and_lap calls math_diff_2r_9point, math_diff_2z_9point, math_diff_r_9point, math_diff_z_9point, volume_integrate
calc_hpsi calls calc_bpsi, calc_upsi, calc_wpsi
calc_hpsi2 calls math_diff_2r_9point, math_diff_2z_9point, math_diff_r_9point, math_diff_z_9point
calc_kinetic_energy_by_integrate calls volume_integrate
calc_one_particle_energy calls volume_integrate
calc_pot_u calls calc_pot_u_np
calc_skyrme_energy_by_integrate calls volume_integrate
calc_spin_orbit_density_and_div calls math_diff_r_9point, math_diff_z_9point
schmidt_orthogonalization calls prep_wf_overlap
set_harmonic_occ calls hermite_n, laguerre_nl
calc_bpsi calls math_diff_r_9point, math_diff_z_9point
calc_pc2_exv calls volume_integrate
calc_pot_u_np calls b0pt, b0t, b1pt, b1t, b2pt, b2t, b3pt, b3pt2, b3t, b4pt, b4t, calc_coulomb_pot, write_u_term
prep_wf_overlap calls volume_integrate
calc_coulomb_pot calls nine_point_poisson_by_lapack
nine_point_poisson_by_lapack calls get_k, use_dgesv
use_dgesv calls dgesv