calc_pot_U_np – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
calc_pot_U_np Subroutine
101 statements
Source File
public subroutine calc_pot_U_np(np_str, is_coulomb)
Uses
write_to_file
global_variables
iso_fortran_env
constants_and_parameters
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: np_str
logical, intent(in), optional :: is_coulomb
Calls
Called by
Contents
Call graph
calc_pot_u_np calls b0pt, b0t, b1pt, b1t, b2pt, b2t, b3pt, b3pt2, b3t, b4pt, b4t, calc_coulomb_pot, write_u_term
calc_coulomb_pot calls nine_point_poisson_by_lapack
nine_point_poisson_by_lapack calls get_k, use_dgesv
use_dgesv calls dgesv
calc_pot_u calls calc_pot_u_np
calc_meanfield calls calc_pot_u
calc_ground_state calls calc_meanfield
main calls calc_ground_state