calc_densities – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
calc_densities Subroutine
6 statements
Source File
subroutine calc_densities()
Arguments
None
Calls
Called by
Contents
None
Call graph
calc_densities calls calc_density_and_lap, calc_kinetic_density, calc_spin_orbit_density_and_div
calc_density_and_lap calls math_diff_2r_9point, math_diff_2z_9point, math_diff_r_9point, math_diff_z_9point, volume_integrate
calc_spin_orbit_density_and_div calls math_diff_r_9point, math_diff_z_9point
math_diff_2r_9point calls math_diff_2r_9point_realfunc
math_diff_2z_9point calls math_diff_2z_9point_realfunc
math_diff_r_9point calls math_diff_r_9point_complexfunc, math_diff_r_9point_realfunc
math_diff_z_9point calls math_diff_z_9point_complexfunc, math_diff_z_9point_realfunc
calc_ground_state calls calc_densities
main calls calc_ground_state