initial_settings – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
initial_settings Subroutine
17 statements
Source File
subroutine initial_settings()
Uses
global_variables
iso_fortran_env
Arguments
None
Calls
Called by
Contents
None
Call graph
initial_settings calls prep_initial_wavefunction, prep_time_reversal_wavefunction
prep_initial_wavefunction calls calc_occ_energy, set_harmonic_occ, sort_energy_and_idx
prep_time_reversal_wavefunction calls calc_occ_energy, set_harmonic_occ, sort_energy_and_idx
set_harmonic_occ calls hermite_n, laguerre_nl
main calls initial_settings