prep_initial_wavefunction – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
prep_initial_wavefunction Subroutine
70 statements
Source File
subroutine prep_initial_wavefunction()
Uses
harmonic_occ_wf
global_variables
math_integrate
iso_fortran_env
constants_and_parameters
!!!!--------- prep_numberも変更してます -----------！！！！！！！！！！！
Arguments
None
Calls
Called by
Contents
None
Call graph
prep_initial_wavefunction calls calc_occ_energy, set_harmonic_occ, sort_energy_and_idx
set_harmonic_occ calls hermite_n, laguerre_nl
initial_settings calls prep_initial_wavefunction
main calls initial_settings