math_diff_r_9point – Axial Skyrme Hartree-Fock (SHF) Code using Fortran Free-Form.
math_diff_r_9point Interface
3 statements
Source File
public interface math_diff_r_9point
Calls
Called by
Contents
Module Procedures
math_diff_r_9point_realfunc math_diff_r_9point_complexfunc
Module Procedures
public function math_diff_r_9point_realfunc(f) result(f_r)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: f(:,:)
Return Value real(kind=real64), allocatable, (:,:)
public function math_diff_r_9point_complexfunc(f) result(f_r)
Arguments
Type Intent Optional Attributes Name
complex(kind=real64), intent(in) :: f(:,:)
Return Value complex(kind=real64), allocatable, (:,:)
Call graph
math_diff_r_9point calls math_diff_r_9point_complexfunc, math_diff_r_9point_realfunc
calc_bpsi calls math_diff_r_9point
calc_density_and_lap calls math_diff_r_9point
calc_derivation_of_wavefunction calls math_diff_r_9point
calc_hpsi2 calls math_diff_r_9point
calc_spin_orbit_density_and_div calls math_diff_r_9point
calc_densities calls calc_density_and_lap, calc_spin_orbit_density_and_div
calc_ground_state calls calc_derivation_of_wavefunction, calc_densities, calc_hf_by_imaginary_time_evolution
calc_hf_by_imaginary_time_evolution calls calc_hpsi2, calc_hpsi
calc_hpsi calls calc_bpsi
main calls calc_ground_state